// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_shocking = "CgkIx5zQq6YGEAIQBA"; // <GPGSID>
        public const string achievement_invincible = "CgkIx5zQq6YGEAIQAw"; // <GPGSID>
        public const string event_upgrade_refunded = "CgkIx5zQq6YGEAIQCw"; // <GPGSID>
        public const string achievement_against_all_odds = "CgkIx5zQq6YGEAIQAg"; // <GPGSID>
        public const string event_powerup_chosen = "CgkIx5zQq6YGEAIQBg"; // <GPGSID>
        public const string achievement_i_feel_something_a_slight_tingle_in_my_generator = "CgkIx5zQq6YGEAIQBQ"; // <GPGSID>
        public const string event_upgrade_purchased = "CgkIx5zQq6YGEAIQCQ"; // <GPGSID>
        public const string event_coin_collected = "CgkIx5zQq6YGEAIQBw"; // <GPGSID>
        public const string achievement_carrier_has_departed = "CgkIx5zQq6YGEAIQAQ"; // <GPGSID>
        public const string event_challenge_activated = "CgkIx5zQq6YGEAIQCg"; // <GPGSID>
        public const string event_trophy_collected = "CgkIx5zQq6YGEAIQCA"; // <GPGSID>

}

